/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

public class AdminLand extends javax.swing.JFrame {

   private InfDB idb;
   
     
    public AdminLand(InfDB idb){
        initComponents();
        this.idb = idb;
        
     
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRaderaLand = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableLand = new javax.swing.JTable();
        BtnTbxAdMeny1 = new javax.swing.JButton();
        JlrubrikPartners = new javax.swing.JLabel();
        PanelNyttLand = new javax.swing.JPanel();
        jlNamn = new javax.swing.JLabel();
        tfValuta = new javax.swing.JTextField();
        jLSprak = new javax.swing.JLabel();
        jLValuta = new javax.swing.JLabel();
        jLPolitiskStruktur = new javax.swing.JLabel();
        jLTidszon = new javax.swing.JLabel();
        tfNamn = new javax.swing.JTextField();
        tfTidszon = new javax.swing.JTextField();
        tfPolitiskStruktur = new javax.swing.JTextField();
        tfSprak = new javax.swing.JTextField();
        BtnLaggTill3 = new javax.swing.JButton();
        tfEkonomi = new javax.swing.JTextField();
        jLEkonomi = new javax.swing.JLabel();
        BtnAndraLand = new javax.swing.JButton();
        BtnHamtaLand = new javax.swing.JButton();
        tfHamtaLand = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnRaderaLand.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnRaderaLand.setForeground(new java.awt.Color(255, 0, 0));
        BtnRaderaLand.setText("Radera");
        BtnRaderaLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRaderaLandActionPerformed(evt);
            }
        });

        TableLand.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TableLand.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Namn", "Språk", "Valuta", "Politisk struktur", "Tidszon", "Ekonomi"
            }
        ));
        jScrollPane2.setViewportView(TableLand);

        BtnTbxAdMeny1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnTbxAdMeny1.setForeground(new java.awt.Color(0, 0, 102));
        BtnTbxAdMeny1.setText("Tillbaka");
        BtnTbxAdMeny1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTbxAdMeny1ActionPerformed(evt);
            }
        });

        JlrubrikPartners.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JlrubrikPartners.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JlrubrikPartners.setText("Lista över länder:");

        PanelNyttLand.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nytt land", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        PanelNyttLand.setOpaque(false);

        jlNamn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlNamn.setText("Namn");

        tfValuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValutaActionPerformed(evt);
            }
        });

        jLSprak.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLSprak.setText("Språk");

        jLValuta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLValuta.setText("Valuta");

        jLPolitiskStruktur.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLPolitiskStruktur.setText("Politisk struktur");

        jLTidszon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTidszon.setText("Tidszon");

        BtnLaggTill3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnLaggTill3.setForeground(new java.awt.Color(0, 0, 102));
        BtnLaggTill3.setText("Lägg till");
        BtnLaggTill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaggTill3ActionPerformed(evt);
            }
        });

        jLEkonomi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEkonomi.setText("Ekonomi");

        BtnAndraLand.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnAndraLand.setForeground(new java.awt.Color(255, 0, 0));
        BtnAndraLand.setText("Ändra");
        BtnAndraLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAndraLandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNyttLandLayout = new javax.swing.GroupLayout(PanelNyttLand);
        PanelNyttLand.setLayout(PanelNyttLandLayout);
        PanelNyttLandLayout.setHorizontalGroup(
            PanelNyttLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNyttLandLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelNyttLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEkonomi)
                    .addComponent(tfTidszon)
                    .addGroup(PanelNyttLandLayout.createSequentialGroup()
                        .addGroup(PanelNyttLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLEkonomi)
                            .addComponent(jLPolitiskStruktur)
                            .addComponent(jLValuta)
                            .addComponent(jLSprak)
                            .addComponent(jLTidszon)
                            .addComponent(jlNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfPolitiskStruktur)
                    .addComponent(tfValuta)
                    .addComponent(tfSprak)
                    .addComponent(tfNamn)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNyttLandLayout.createSequentialGroup()
                        .addComponent(BtnAndraLand, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(BtnLaggTill3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelNyttLandLayout.setVerticalGroup(
            PanelNyttLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNyttLandLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlNamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLSprak)
                .addGap(12, 12, 12)
                .addComponent(tfSprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLValuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLPolitiskStruktur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPolitiskStruktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLTidszon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTidszon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLEkonomi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(PanelNyttLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLaggTill3)
                    .addComponent(BtnAndraLand))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        BtnHamtaLand.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnHamtaLand.setForeground(new java.awt.Color(0, 0, 102));
        BtnHamtaLand.setText("Hämta");
        BtnHamtaLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHamtaLandActionPerformed(evt);
            }
        });

        tfHamtaLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHamtaLandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnTbxAdMeny1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JlrubrikPartners, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PanelNyttLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfHamtaLand, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnHamtaLand, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRaderaLand, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(49, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlrubrikPartners)
                    .addComponent(BtnTbxAdMeny1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(tfHamtaLand)
                    .addComponent(BtnHamtaLand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnRaderaLand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelNyttLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTbxAdMeny1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTbxAdMeny1ActionPerformed
        new AdminMeny(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTbxAdMeny1ActionPerformed

    private void tfValutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValutaActionPerformed

    private void BtnLaggTill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaggTill3ActionPerformed
        String namn = tfNamn.getText();
        String sprak = tfSprak.getText();
        String valuta = tfValuta.getText();
        String politiskStruktur = tfPolitiskStruktur.getText();
        String tidszon = tfTidszon.getText();
        String ekonomi = tfEkonomi.getText();
  
    if (namn.isEmpty() || sprak.isEmpty() || valuta.isEmpty()|| politiskStruktur.isEmpty()|| tidszon.isEmpty() || ekonomi.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Fyll i alla fält!", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    DefaultTableModel tableModel = (DefaultTableModel) TableLand.getModel();
    tableModel.addRow(new Object[]{namn, sprak, valuta, politiskStruktur, tidszon, ekonomi,});

    tfNamn.setText("");
    tfSprak.setText("");
    tfValuta.setText("");
    tfPolitiskStruktur.setText("");
    tfTidszon.setText("");
    tfEkonomi.setText("");
    
         
    }//GEN-LAST:event_BtnLaggTill3ActionPerformed

    private void BtnRaderaLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRaderaLandActionPerformed
 int selectedRow = TableLand.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "välj en rad att radera!", "fel", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) TableLand.getModel();
        model.removeRow(selectedRow); 
    }//GEN-LAST:event_BtnRaderaLandActionPerformed

    private void BtnHamtaLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHamtaLandActionPerformed
        String searchInput = tfHamtaLand.getText().trim();
    
        if (searchInput.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ange ett land att söka efter.");
        return;    
    }

    try { 
       String sql = "SELECT namn, sprak, valuta, politisk_struktur, tidszon, ekonomi " +
                    "FROM land " +
                    "WHERE namn LIKE '%" + searchInput + "%' " +
                    "OR sprak LIKE '%" + searchInput + "%' " +
                    "OR valuta LIKE '%" + searchInput + "%'";

        ArrayList<HashMap<String, String>> countries = idb.fetchRows(sql);

        DefaultTableModel model = (DefaultTableModel) TableLand.getModel();
        model.setRowCount(0);

        if (countries != null && !countries.isEmpty()) {
           for (HashMap<String, String> country : countries) {
             model.addRow(new Object[]{
                  country.get("namn"),
                  country.get("sprak"),
                  country.get("valuta"),
                  country.get("politisk_struktur"),
                  country.get("tidszon"),
                  country.get("ekonomi")
              });
           }
       } else {
             JOptionPane.showMessageDialog(this, "Inga resultat hittades för: " + searchInput);
             
       }

       
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Ett fel inträffade vid sökning: " + ex.getMessage());
        ex.printStackTrace();
      }
    }//GEN-LAST:event_BtnHamtaLandActionPerformed

    private void BtnAndraLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAndraLandActionPerformed
        //Hämtar vald rad i tabellen
        int selectedRow = TableLand.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TableLand.getModel();

       
        if (selectedRow != -1) { //Kontrollerar om en rad blivit vald
          
           // Hämtar nya värden från textFälten, men behåller den gamla infon om fältet är tomt
           String nyttNamn = tfNamn.getText().isEmpty() ? model.getValueAt(selectedRow, 0).toString() : tfNamn.getText();
           String nyttSprak = tfSprak.getText().isEmpty() ? model.getValueAt(selectedRow, 1).toString() : tfSprak.getText();
           String nyValuta = tfValuta.getText().isEmpty() ? model.getValueAt(selectedRow, 2).toString() : tfValuta.getText();
           String nyPolitiskStruktur = tfPolitiskStruktur.getText().isEmpty() ? model.getValueAt(selectedRow, 3).toString() : tfPolitiskStruktur.getText();
           String nyTidszon = tfTidszon.getText().isEmpty() ? model.getValueAt(selectedRow, 4).toString() : tfTidszon.getText();
           String nyEkonomi = tfEkonomi.getText().isEmpty() ? model.getValueAt(selectedRow, 5).toString() : tfEkonomi.getText();

           
           // Uppdaterar tabellens modell med de nya värdena
           model.setValueAt(nyttNamn, selectedRow, 0);
           model.setValueAt(nyttSprak, selectedRow, 1);
           model.setValueAt(nyValuta, selectedRow, 2);
           model.setValueAt(nyPolitiskStruktur, selectedRow, 3);
           model.setValueAt(nyTidszon, selectedRow, 4);
           model.setValueAt(nyEkonomi, selectedRow, 5);
           
           // Bekräftelsemeddelande
           JOptionPane.showMessageDialog(null, "Landet har uppdaterats!", "Ändrat", JOptionPane.INFORMATION_MESSAGE);
        } else {
           // Om ingen rad är vald
           JOptionPane.showMessageDialog(null, "Välj ett land att ändra!", "Fel", JOptionPane.WARNING_MESSAGE);
        }
    

 
    }//GEN-LAST:event_BtnAndraLandActionPerformed

    private void tfHamtaLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHamtaLandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHamtaLandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminLand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAndraLand;
    private javax.swing.JButton BtnHamtaLand;
    private javax.swing.JButton BtnLaggTill3;
    private javax.swing.JButton BtnRaderaLand;
    private javax.swing.JButton BtnTbxAdMeny1;
    private javax.swing.JLabel JlrubrikPartners;
    private javax.swing.JPanel PanelNyttLand;
    private javax.swing.JTable TableLand;
    private javax.swing.JLabel jLEkonomi;
    private javax.swing.JLabel jLPolitiskStruktur;
    private javax.swing.JLabel jLSprak;
    private javax.swing.JLabel jLTidszon;
    private javax.swing.JLabel jLValuta;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlNamn;
    private javax.swing.JTextField tfEkonomi;
    private javax.swing.JTextField tfHamtaLand;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfPolitiskStruktur;
    private javax.swing.JTextField tfSprak;
    private javax.swing.JTextField tfTidszon;
    private javax.swing.JTextField tfValuta;
    // End of variables declaration//GEN-END:variables
}
