/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

public class AdminLand extends javax.swing.JFrame {

   private InfDB idb;
   
     
    public AdminLand(InfDB idb){
        initComponents();
        this.idb = idb;
        
     
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableLand = new javax.swing.JTable();
        BtnTbxAdMeny1 = new javax.swing.JButton();
        JlrubrikPartners = new javax.swing.JLabel();
        PanelNyttLand = new javax.swing.JPanel();
        jlNamn = new javax.swing.JLabel();
        tfValuta = new javax.swing.JTextField();
        jLSprak = new javax.swing.JLabel();
        jLValuta = new javax.swing.JLabel();
        jLPolitiskStruktur = new javax.swing.JLabel();
        jLTidszon = new javax.swing.JLabel();
        tfNamn = new javax.swing.JTextField();
        tfTidszon = new javax.swing.JTextField();
        tfPolitiskStruktur = new javax.swing.JTextField();
        tfSprak = new javax.swing.JTextField();
        BtnRensa3 = new javax.swing.JButton();
        BtnLaggTill3 = new javax.swing.JButton();
        tfEkonomi = new javax.swing.JTextField();
        jLEkonomi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Radera");

        TableLand.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TableLand.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Namn", "Språk", "Valuta", "Politisk struktur", "Tidszon", "Ekonomi"
            }
        ));
        jScrollPane2.setViewportView(TableLand);

        BtnTbxAdMeny1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnTbxAdMeny1.setForeground(new java.awt.Color(0, 0, 102));
        BtnTbxAdMeny1.setText("Tillbaka");
        BtnTbxAdMeny1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTbxAdMeny1ActionPerformed(evt);
            }
        });

        JlrubrikPartners.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JlrubrikPartners.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JlrubrikPartners.setText("Lista över länder:");

        PanelNyttLand.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nytt land", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        PanelNyttLand.setOpaque(false);

        jlNamn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlNamn.setText("Namn");

        tfValuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValutaActionPerformed(evt);
            }
        });

        jLSprak.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLSprak.setText("Språk");

        jLValuta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLValuta.setText("Valuta");

        jLPolitiskStruktur.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLPolitiskStruktur.setText("Politisk struktur");

        jLTidszon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTidszon.setText("Tidszon");

        BtnRensa3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnRensa3.setForeground(new java.awt.Color(255, 0, 0));
        BtnRensa3.setText("Rensa");

        BtnLaggTill3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnLaggTill3.setText("Lägg till");
        BtnLaggTill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaggTill3ActionPerformed(evt);
            }
        });

        jLEkonomi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLEkonomi.setText("Ekonomi");

        javax.swing.GroupLayout PanelNyttLandLayout = new javax.swing.GroupLayout(PanelNyttLand);
        PanelNyttLand.setLayout(PanelNyttLandLayout);
        PanelNyttLandLayout.setHorizontalGroup(
            PanelNyttLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNyttLandLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelNyttLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEkonomi)
                    .addGroup(PanelNyttLandLayout.createSequentialGroup()
                        .addComponent(BtnRensa3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(BtnLaggTill3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfTidszon)
                    .addGroup(PanelNyttLandLayout.createSequentialGroup()
                        .addGroup(PanelNyttLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLEkonomi)
                            .addComponent(jLPolitiskStruktur)
                            .addComponent(jLValuta)
                            .addComponent(jLSprak)
                            .addComponent(jLTidszon)
                            .addComponent(jlNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tfPolitiskStruktur)
                    .addComponent(tfValuta)
                    .addComponent(tfSprak)
                    .addComponent(tfNamn))
                .addContainerGap())
        );
        PanelNyttLandLayout.setVerticalGroup(
            PanelNyttLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNyttLandLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlNamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLSprak)
                .addGap(12, 12, 12)
                .addComponent(tfSprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLValuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLPolitiskStruktur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPolitiskStruktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLTidszon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTidszon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLEkonomi)
                .addGap(20, 20, 20)
                .addComponent(tfEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(PanelNyttLandLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRensa3)
                    .addComponent(BtnLaggTill3))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BtnTbxAdMeny1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JlrubrikPartners, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelNyttLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlrubrikPartners)
                    .addComponent(BtnTbxAdMeny1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(PanelNyttLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTbxAdMeny1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTbxAdMeny1ActionPerformed
        new MenyAdmin(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTbxAdMeny1ActionPerformed

    private void tfValutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValutaActionPerformed

    private void BtnLaggTill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaggTill3ActionPerformed
        String namn = tfNamn.getText();
        String sprak = tfSprak.getText();
        String valuta = tfValuta.getText();
        String tidszon = tfTidszon.getText();
        String ekonomi = tfEkonomi.getText();
        String politiskStruktur = tfPolitiskStruktur.getText();
  
    if (namn.isEmpty() || sprak.isEmpty() || tidszon.isEmpty()|| politiskStruktur.isEmpty()|| valuta.isEmpty() || ekonomi.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Fyll i alla fält!", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    DefaultTableModel tableModel = (DefaultTableModel) TableLand.getModel();
    tableModel.addRow(new Object[]{namn, sprak, valuta, ekonomi, tidszon, politiskStruktur,});

    tfNamn.setText("");
    tfSprak.setText("");
    tfValuta.setText("");
    tfTidszon.setText("");
    tfEkonomi.setText("");
    tfPolitiskStruktur.setText("");
    
         
    }//GEN-LAST:event_BtnLaggTill3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLand.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminLand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLaggTill3;
    private javax.swing.JButton BtnRensa3;
    private javax.swing.JButton BtnTbxAdMeny1;
    private javax.swing.JLabel JlrubrikPartners;
    private javax.swing.JPanel PanelNyttLand;
    private javax.swing.JTable TableLand;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLEkonomi;
    private javax.swing.JLabel jLPolitiskStruktur;
    private javax.swing.JLabel jLSprak;
    private javax.swing.JLabel jLTidszon;
    private javax.swing.JLabel jLValuta;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlNamn;
    private javax.swing.JTextField tfEkonomi;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfPolitiskStruktur;
    private javax.swing.JTextField tfSprak;
    private javax.swing.JTextField tfTidszon;
    private javax.swing.JTextField tfValuta;
    // End of variables declaration//GEN-END:variables
}
//HEJ