/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

public class AdminAvdelning extends javax.swing.JFrame {

    private InfDB idb;

    public AdminAvdelning(InfDB idb) {
        initComponents();
        this.idb = idb;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRadera = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAvdelning = new javax.swing.JTable();
        BtnTbxFranAvd = new javax.swing.JButton();
        JlrubrikAvdelning = new javax.swing.JLabel();
        PanelNyAvdelning = new javax.swing.JPanel();
        jlNamn = new javax.swing.JLabel();
        tfAdress = new javax.swing.JTextField();
        jLePost = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLTelefon = new javax.swing.JLabel();
        jLStad = new javax.swing.JLabel();
        tfNamn = new javax.swing.JTextField();
        tfBeskrivning = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        tfEpost = new javax.swing.JTextField();
        BtnRensa = new javax.swing.JButton();
        BtnLaggTill = new javax.swing.JButton();
        tfStad = new javax.swing.JTextField();
        tfAvdelningschef = new javax.swing.JTextField();
        jLBeskrivning = new javax.swing.JLabel();
        jLAvdelningschef = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnRadera.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnRadera.setForeground(new java.awt.Color(255, 0, 51));
        BtnRadera.setText("Radera");

        TableAvdelning.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TableAvdelning.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Namn", "Epost", "Adress", "Telefon", "Beskrivning", "Avdelningschef"
            }
        ));
        jScrollPane2.setViewportView(TableAvdelning);

        BtnTbxFranAvd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnTbxFranAvd.setForeground(new java.awt.Color(0, 0, 102));
        BtnTbxFranAvd.setText("Tillbaka");
        BtnTbxFranAvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTbxFranAvdActionPerformed(evt);
            }
        });

        JlrubrikAvdelning.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JlrubrikAvdelning.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JlrubrikAvdelning.setText("Lista över avdelningar:");

        PanelNyAvdelning.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ny avdelning", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        PanelNyAvdelning.setOpaque(false);

        jlNamn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlNamn.setText("Namn");

        tfAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAdressActionPerformed(evt);
            }
        });

        jLePost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLePost.setText("Epost");

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel34.setText("Adress");

        jLTelefon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTelefon.setText("Telefon");

        jLStad.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLStad.setText("Stad");

        BtnRensa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnRensa.setForeground(new java.awt.Color(255, 0, 51));
        BtnRensa.setText("Rensa");

        BtnLaggTill.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnLaggTill.setText("Lägg till");
        BtnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaggTillActionPerformed(evt);
            }
        });

        jLBeskrivning.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLBeskrivning.setText("Beskrivning");

        jLAvdelningschef.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLAvdelningschef.setText("Avdelningschef");

        javax.swing.GroupLayout PanelNyAvdelningLayout = new javax.swing.GroupLayout(PanelNyAvdelning);
        PanelNyAvdelning.setLayout(PanelNyAvdelningLayout);
        PanelNyAvdelningLayout.setHorizontalGroup(
            PanelNyAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNyAvdelningLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelNyAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLAvdelningschef)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTelefon)
                    .addComponent(jLabel34)
                    .addComponent(jLePost)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStad)
                    .addComponent(tfStad, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBeskrivning)
                    .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelNyAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelNyAvdelningLayout.createSequentialGroup()
                            .addComponent(BtnRensa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tfAvdelningschef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        PanelNyAvdelningLayout.setVerticalGroup(
            PanelNyAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNyAvdelningLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlNamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLePost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLTelefon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLStad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLAvdelningschef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAvdelningschef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(PanelNyAvdelningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRensa)
                    .addComponent(BtnLaggTill))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BtnTbxFranAvd, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(JlrubrikAvdelning))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(PanelNyAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnRadera, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlrubrikAvdelning)
                    .addComponent(BtnTbxFranAvd))
                .addGap(18, 18, 18)
                .addComponent(BtnRadera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelNyAvdelning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTbxFranAvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTbxFranAvdActionPerformed
        new MenyAdmin(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTbxFranAvdActionPerformed

    private void tfAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAdressActionPerformed

    private void BtnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaggTillActionPerformed
        String namn = tfNamn.getText();
        String telefon = tfTelefon.getText();
        String adress = tfAdress.getText();
        String epost= tfEpost.getText();
        String stad = tfStad.getText();
        String beskrivning = tfBeskrivning.getText();
        String avdelningschef = tfAvdelningschef.getText();

    if (namn.isEmpty() || telefon.isEmpty() || adress.isEmpty()|| epost.isEmpty()|| stad.isEmpty() ||  beskrivning.isEmpty() || avdelningschef.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Fyll i alla fält!", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Lägg till rad i tabellen
    DefaultTableModel tableModel = (DefaultTableModel) TableAvdelning.getModel();
    tableModel.addRow(new Object[]{namn, telefon, adress, epost, stad, beskrivning, avdelningschef,});

    // Rensa fälten efter tillägg
    tfNamn.setText("");
    tfTelefon.setText("");
    tfAdress.setText("");
    tfEpost.setText("");
    tfStad.setText("");
    tfBeskrivning.setText("");
    tfAvdelningschef.setText("");
    }//GEN-LAST:event_BtnLaggTillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAvdelning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminAvdelning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLaggTill;
    private javax.swing.JButton BtnLaggTill1;
    private javax.swing.JButton BtnLaggTill2;
    private javax.swing.JButton BtnLaggTill3;
    private javax.swing.JButton BtnLaggTill4;
    private javax.swing.JButton BtnLaggTill5;
    private javax.swing.JButton BtnRadera;
    private javax.swing.JButton BtnRensa;
    private javax.swing.JButton BtnRensa1;
    private javax.swing.JButton BtnRensa2;
    private javax.swing.JButton BtnRensa3;
    private javax.swing.JButton BtnRensa4;
    private javax.swing.JButton BtnRensa5;
    private javax.swing.JButton BtnTbxFranAvd;
    private javax.swing.JLabel JlrubrikAvdelning;
    private javax.swing.JPanel PanelNyAvdelning;
    private javax.swing.JTable TableAvdelning;
    private javax.swing.JLabel jLAvdelningschef;
    private javax.swing.JLabel jLBeskrivning;
    private javax.swing.JLabel jLStad;
    private javax.swing.JLabel jLTelefon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLePost;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel jlNamn;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAvdelningschef;
    private javax.swing.JTextField tfBeskrivning;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfStad;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
