/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;

public class AdminAnstalld extends javax.swing.JFrame {

    private InfDB idb;
    
    public AdminAnstalld(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnTillbaka = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMedarbetare = new javax.swing.JTable();
        javax.swing.JPanel PanelNyMedarbetare = new javax.swing.JPanel();
        javax.swing.JLabel jLNamn = new javax.swing.JLabel();
        tfNamn2 = new javax.swing.JTextField();
        javax.swing.JLabel JlePost = new javax.swing.JLabel();
        tfEpost2 = new javax.swing.JTextField();
        javax.swing.JLabel jLTelefon = new javax.swing.JLabel();
        tfTelefon2 = new javax.swing.JTextField();
        javax.swing.JLabel jLAdress = new javax.swing.JLabel();
        tfAdress2 = new javax.swing.JTextField();
        javax.swing.JButton btnLaggTill2 = new javax.swing.JButton();
        javax.swing.JButton btnRensa2 = new javax.swing.JButton();
        javax.swing.JButton btnRadera1 = new javax.swing.JButton();
        javax.swing.JLabel jLRubrik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnTillbaka.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnTillbaka.setForeground(new java.awt.Color(0, 0, 102));
        BtnTillbaka.setText("Tillbaka");
        BtnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTillbakaActionPerformed(evt);
            }
        });

        tableMedarbetare.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tableMedarbetare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Namn", "E-Post", "Telefon", "Adress"
            }
        ));
        jScrollPane3.setViewportView(tableMedarbetare);

        PanelNyMedarbetare.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ny anställd", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        PanelNyMedarbetare.setOpaque(false);

        jLNamn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLNamn.setText("Namn");

        JlePost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JlePost.setText("E-Post");

        jLTelefon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTelefon.setText("Telefon");

        jLAdress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLAdress.setText("Adress");

        btnLaggTill2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLaggTill2.setText("Lägg till");
        btnLaggTill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTill2btnLaggTillActionPerformed(evt);
            }
        });

        btnRensa2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRensa2.setForeground(new java.awt.Color(255, 0, 0));
        btnRensa2.setText("Rensa");
        btnRensa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensa2btnRensaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNyMedarbetareLayout = new javax.swing.GroupLayout(PanelNyMedarbetare);
        PanelNyMedarbetare.setLayout(PanelNyMedarbetareLayout);
        PanelNyMedarbetareLayout.setHorizontalGroup(
            PanelNyMedarbetareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNyMedarbetareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNyMedarbetareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNamn2)
                    .addComponent(JlePost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfEpost2)
                    .addComponent(jLTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTelefon2)
                    .addComponent(jLAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfAdress2)
                    .addGroup(PanelNyMedarbetareLayout.createSequentialGroup()
                        .addComponent(btnRensa2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnLaggTill2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelNyMedarbetareLayout.setVerticalGroup(
            PanelNyMedarbetareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNyMedarbetareLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tfNamn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JlePost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEpost2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLTelefon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTelefon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLAdress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAdress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(PanelNyMedarbetareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRensa2)
                    .addComponent(btnLaggTill2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRadera1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRadera1.setForeground(new java.awt.Color(255, 51, 51));
        btnRadera1.setText("Radera");
        btnRadera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadera1ActionPerformed(evt);
            }
        });

        jLRubrik.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLRubrik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLRubrik.setText("Lista över anställda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelNyMedarbetare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRadera1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BtnTillbaka))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLRubrik)))
                .addGap(24, 24, 24)
                .addComponent(btnRadera1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelNyMedarbetare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTillbakaActionPerformed
        new MenyAdmin(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTillbakaActionPerformed

    private void btnLaggTill2btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTill2btnLaggTillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaggTill2btnLaggTillActionPerformed

    private void btnRensa2btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensa2btnRensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRensa2btnRensaActionPerformed

    private void btnRadera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadera1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRadera1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAnstalld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminAnstalld().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTillbaka;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableMedarbetare;
    private javax.swing.JTextField tfAdress2;
    private javax.swing.JTextField tfEpost2;
    private javax.swing.JTextField tfNamn2;
    private javax.swing.JTextField tfTelefon2;
    // End of variables declaration//GEN-END:variables
}
