/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import java.util.ArrayList;



public class AdminMedarbetare extends javax.swing.JFrame {

    
    private InfDB idb;

    /**
     * Creates new form MainFrame1
     */
    public AdminMedarbetare(InfDB idb) {
        this.idb = idb;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLRubrik = new javax.swing.JLabel();
        javax.swing.JPanel PanelNyMedarbetare = new javax.swing.JPanel();
        javax.swing.JLabel jLNamn = new javax.swing.JLabel();
        tfNamn2 = new javax.swing.JTextField();
        javax.swing.JLabel JlePost = new javax.swing.JLabel();
        tfEpost2 = new javax.swing.JTextField();
        javax.swing.JLabel jLTelefon = new javax.swing.JLabel();
        tfTelefon2 = new javax.swing.JTextField();
        javax.swing.JLabel jLAdress = new javax.swing.JLabel();
        tfAdress2 = new javax.swing.JTextField();
        javax.swing.JButton btnLaggTill2 = new javax.swing.JButton();
        javax.swing.JButton btnRensa2 = new javax.swing.JButton();
        javax.swing.JButton btnRadera1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMedarbetare = new javax.swing.JTable();
        BtnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setMinimumSize(new java.awt.Dimension(812, 563));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLRubrik.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLRubrik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLRubrik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/ännu bättre.png"))); // NOI18N
        jLRubrik.setText("Lista över medarbetare:");

        PanelNyMedarbetare.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ny medarbetare", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        PanelNyMedarbetare.setOpaque(false);

        jLNamn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLNamn.setText("Namn");

        JlePost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JlePost.setText("E-Post");

        jLTelefon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTelefon.setText("Telefon");

        jLAdress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLAdress.setText("Adress");

        btnLaggTill2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnLaggTill2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/add.png"))); // NOI18N
        btnLaggTill2.setText("Lägg till");
        btnLaggTill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTill2btnLaggTillActionPerformed(evt);
            }
        });

        btnRensa2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRensa2.setForeground(new java.awt.Color(255, 0, 0));
        btnRensa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/rubber.png"))); // NOI18N
        btnRensa2.setText("Rensa");
        btnRensa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensa2btnRensaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNyMedarbetareLayout = new javax.swing.GroupLayout(PanelNyMedarbetare);
        PanelNyMedarbetare.setLayout(PanelNyMedarbetareLayout);
        PanelNyMedarbetareLayout.setHorizontalGroup(
            PanelNyMedarbetareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNyMedarbetareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNyMedarbetareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfNamn2)
                    .addComponent(JlePost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfEpost2)
                    .addComponent(jLTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTelefon2)
                    .addComponent(jLAdress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfAdress2)
                    .addGroup(PanelNyMedarbetareLayout.createSequentialGroup()
                        .addComponent(btnRensa2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnLaggTill2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelNyMedarbetareLayout.setVerticalGroup(
            PanelNyMedarbetareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNyMedarbetareLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tfNamn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JlePost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEpost2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLTelefon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTelefon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLAdress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAdress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(PanelNyMedarbetareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRensa2)
                    .addComponent(btnLaggTill2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRadera1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRadera1.setForeground(new java.awt.Color(255, 51, 51));
        btnRadera1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ngo2024/trash.png"))); // NOI18N
        btnRadera1.setText("Radera");
        btnRadera1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadera1ActionPerformed(evt);
            }
        });

        tableMedarbetare.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tableMedarbetare.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Namn", "E-Post", "Telefon", "Adress"
            }
        ));
        jScrollPane3.setViewportView(tableMedarbetare);

        BtnTillbaka.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnTillbaka.setForeground(new java.awt.Color(0, 0, 102));
        BtnTillbaka.setText("Tillbaka");
        BtnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelNyMedarbetare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRadera1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(BtnTillbaka))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLRubrik)))
                .addGap(24, 24, 24)
                .addComponent(btnRadera1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelNyMedarbetare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        DefaultTableModel model = (DefaultTableModel) tableMedarbetare.getModel();
        Vector<Vector> tableData = model.getDataVector();
        
        try {
            FileOutputStream file = new FileOutputStream("file.bin");
            ObjectOutputStream output = new ObjectOutputStream(file);
            
            
            
             output.writeObject(tableData);
            
            
          
            output.close();
            file.close();
        }  catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
             DefaultTableModel model = (DefaultTableModel) tableMedarbetare.getModel();
             model.setRowCount(0); // Rensa tabellen
            
             String query = "SELECT Namn, Epost, Telefon, Adress FROM Medarbetare";
             ArrayList<HashMap<String, String>> medarbetare = idb.fetchRows(query);

             if (medarbetare != null) {
                 for (HashMap<String, String> row : medarbetare) {
                      model.addRow(new Object[]{row.get("Namn"), row.get("Epost"), row.get("Telefon"), row.get("Adress")});
                 }
             }
          } catch (Exception ex) {
               JOptionPane.showMessageDialog(this, "Kunde inte hämta medarbetare: " + ex.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);

          }
    }//GEN-LAST:event_formWindowOpened

    private void btnLaggTill2btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTill2btnLaggTillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaggTill2btnLaggTillActionPerformed

    private void btnRensa2btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensa2btnRensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRensa2btnRensaActionPerformed

    private void btnRadera1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadera1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRadera1ActionPerformed

    private void BtnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTillbakaActionPerformed
        new MenyAdmin(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTillbakaActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMedarbetare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMedarbetare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMedarbetare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMedarbetare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminMedarbetare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTillbaka;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableMedarbetare;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfAdress2;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfEpost2;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfNamn2;
    private javax.swing.JTextField tfTelefon;
    private javax.swing.JTextField tfTelefon2;
    // End of variables declaration//GEN-END:variables

    //private void close() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    //}

    //private ObjectOutputStream output() {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    //}
}
