/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oru.inf.InfDB;
import oru.inf.InfException;

public class AdminPartner extends javax.swing.JFrame {

    private InfDB idb;
    
    public AdminPartner(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAndra = new javax.swing.JButton();
        BtnTbxAdMeny1 = new javax.swing.JButton();
        JlrubrikPartners = new javax.swing.JLabel();
        PanelPartner = new javax.swing.JPanel();
        jlNamn = new javax.swing.JLabel();
        tfEpost = new javax.swing.JTextField();
        jLTelefon = new javax.swing.JLabel();
        jLePost = new javax.swing.JLabel();
        jLAdress = new javax.swing.JLabel();
        jLStad = new javax.swing.JLabel();
        tfNamn = new javax.swing.JTextField();
        tfStad = new javax.swing.JTextField();
        tfAdress = new javax.swing.JTextField();
        tfTelefon = new javax.swing.JTextField();
        BtnLaggTill1 = new javax.swing.JButton();
        tfBranch = new javax.swing.JTextField();
        jLBranch = new javax.swing.JLabel();
        tfKonPerson = new javax.swing.JTextField();
        jLKontaktPers = new javax.swing.JLabel();
        BtnAndraPart = new javax.swing.JButton();
        BtnRaderaPartner = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablePartner = new javax.swing.JTable();
        BtnHamtaPartner = new javax.swing.JButton();
        tfHamtaPartner = new javax.swing.JTextField();

        BtnAndra.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnAndra.setForeground(new java.awt.Color(255, 0, 0));
        BtnAndra.setText("Ändra");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnTbxAdMeny1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnTbxAdMeny1.setForeground(new java.awt.Color(0, 0, 102));
        BtnTbxAdMeny1.setText("Tillbaka");
        BtnTbxAdMeny1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTbxAdMeny1ActionPerformed(evt);
            }
        });

        JlrubrikPartners.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        JlrubrikPartners.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        JlrubrikPartners.setText("Lista över partners:");

        PanelPartner.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Partner", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        PanelPartner.setOpaque(false);

        jlNamn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlNamn.setText("Namn");

        tfEpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEpostActionPerformed(evt);
            }
        });

        jLTelefon.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLTelefon.setText("Telefon");

        jLePost.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLePost.setText("Epost");

        jLAdress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLAdress.setText("Adress");

        jLStad.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLStad.setText("Stad");

        BtnLaggTill1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnLaggTill1.setForeground(new java.awt.Color(0, 0, 102));
        BtnLaggTill1.setText("Lägg till");
        BtnLaggTill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLaggTill1ActionPerformed(evt);
            }
        });

        jLBranch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLBranch.setText("Branch");

        jLKontaktPers.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLKontaktPers.setText("Kontaktperson");

        BtnAndraPart.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnAndraPart.setForeground(new java.awt.Color(255, 0, 0));
        BtnAndraPart.setText("Ändra");

        javax.swing.GroupLayout PanelPartnerLayout = new javax.swing.GroupLayout(PanelPartner);
        PanelPartner.setLayout(PanelPartnerLayout);
        PanelPartnerLayout.setHorizontalGroup(
            PanelPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPartnerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanelPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfBranch, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLAdress)
                    .addComponent(jLePost)
                    .addComponent(jLTelefon)
                    .addComponent(tfTelefon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfEpost, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfAdress, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLStad)
                    .addComponent(tfNamn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfStad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLBranch)
                    .addComponent(jLKontaktPers)
                    .addComponent(tfKonPerson, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPartnerLayout.createSequentialGroup()
                        .addComponent(BtnAndraPart, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(BtnLaggTill1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPartnerLayout.setVerticalGroup(
            PanelPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPartnerLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jlNamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTelefon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLePost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLAdress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLStad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLBranch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLKontaktPers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfKonPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelPartnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnLaggTill1)
                    .addComponent(BtnAndraPart))
                .addContainerGap())
        );

        BtnRaderaPartner.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnRaderaPartner.setForeground(new java.awt.Color(255, 0, 51));
        BtnRaderaPartner.setText("Radera");

        TablePartner.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TablePartner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Namn", "Telefon", "Epost", "Adress", "Stad", "Branch", "Kontaktperson"
            }
        ));
        jScrollPane2.setViewportView(TablePartner);

        BtnHamtaPartner.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnHamtaPartner.setForeground(new java.awt.Color(0, 0, 102));
        BtnHamtaPartner.setText("Hämta");

        tfHamtaPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHamtaPartnerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnTbxAdMeny1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(JlrubrikPartners, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PanelPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfHamtaPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnHamtaPartner)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnRaderaPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlrubrikPartners)
                    .addComponent(BtnTbxAdMeny1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRaderaPartner)
                    .addComponent(BtnHamtaPartner)
                    .addComponent(tfHamtaPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelPartner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTbxAdMeny1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTbxAdMeny1ActionPerformed
        new MenyAdmin(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTbxAdMeny1ActionPerformed

    private void tfEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEpostActionPerformed

    private void BtnLaggTill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLaggTill1ActionPerformed
        
        String namn = tfNamn.getText();
        String epost = tfEpost.getText();
        String telefon = tfTelefon.getText();
        String adress = tfAdress.getText();
        String stad = tfStad.getText();
        String branch = tfBranch.getText();
        String kontaktperson = tfKonPerson.getText();
  
    if (namn.isEmpty() || epost.isEmpty() || telefon.isEmpty() || adress.isEmpty() || stad.isEmpty() || branch.isEmpty() || kontaktperson.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Fyll i alla fält!", "Fel", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Lägg till rad i tabellen
    DefaultTableModel tableModel = (DefaultTableModel) TablePartner.getModel();
    tableModel.addRow(new Object[]{namn, epost, telefon, adress, stad, branch, kontaktperson});

    // Rensa fälten efter tillägg
    tfNamn.setText("");
    tfEpost.setText("");
    tfTelefon.setText("");
    tfAdress.setText("");
    tfStad.setText("");
    tfBranch.setText("");
    tfKonPerson.setText("");
    }//GEN-LAST:event_BtnLaggTill1ActionPerformed

    private void tfHamtaPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHamtaPartnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHamtaPartnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPartner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminPartner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAndra;
    private javax.swing.JButton BtnAndraPart;
    private javax.swing.JButton BtnHamtaPartner;
    private javax.swing.JButton BtnLaggTill1;
    private javax.swing.JButton BtnRaderaPartner;
    private javax.swing.JButton BtnTbxAdMeny1;
    private javax.swing.JLabel JlrubrikPartners;
    private javax.swing.JPanel PanelPartner;
    private javax.swing.JTable TablePartner;
    private javax.swing.JLabel jLAdress;
    private javax.swing.JLabel jLBranch;
    private javax.swing.JLabel jLKontaktPers;
    private javax.swing.JLabel jLStad;
    private javax.swing.JLabel jLTelefon;
    private javax.swing.JLabel jLePost;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlNamn;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfBranch;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfHamtaPartner;
    private javax.swing.JTextField tfKonPerson;
    private javax.swing.JTextField tfNamn;
    private javax.swing.JTextField tfStad;
    private javax.swing.JTextField tfTelefon;
    // End of variables declaration//GEN-END:variables
}
