/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel; 

/**
 *
 * @author Tyson
 */
public class HandlaggareProjekt extends javax.swing.JFrame {

    /**
     * Creates new form MinaProjekt
     */
    
    
    private InfDB idb;
    
    public HandlaggareProjekt(InfDB idb) {
        initComponents();
        this.idb = idb;
        
        loadProjectData();
    }

    private HandlaggareProjekt() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        TableProjekt = new javax.swing.JTable();
        BtnTbxFrånProjekt = new javax.swing.JButton();
        JlrubrikProjekt = new javax.swing.JLabel();
        tfHamtaProjekt = new javax.swing.JTextField();
        BtnHamtaProjekt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableProjekt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TableProjekt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Projekt", "Startdatum", "Status", "Partners"
            }
        ));
        jScrollPane2.setViewportView(TableProjekt);

        BtnTbxFrånProjekt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnTbxFrånProjekt.setForeground(new java.awt.Color(0, 0, 102));
        BtnTbxFrånProjekt.setText("Tillbaka");
        BtnTbxFrånProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTbxFrånProjektActionPerformed(evt);
            }
        });

        JlrubrikProjekt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JlrubrikProjekt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlrubrikProjekt.setText("Mina Projekt");

        tfHamtaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHamtaProjektActionPerformed(evt);
            }
        });

        BtnHamtaProjekt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnHamtaProjekt.setForeground(new java.awt.Color(0, 0, 102));
        BtnHamtaProjekt.setText("Hämta");
        BtnHamtaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHamtaProjektActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(JlrubrikProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfHamtaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHamtaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(BtnTbxFrånProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(JlrubrikProjekt)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHamtaProjekt)
                    .addComponent(BtnHamtaProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnTbxFrånProjekt)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTbxFrånProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTbxFrånProjektActionPerformed
        new HandlaggareMenyProjekt(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTbxFrånProjektActionPerformed

    private void tfHamtaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHamtaProjektActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHamtaProjektActionPerformed

    private void BtnHamtaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHamtaProjektActionPerformed
        String searchInput = tfHamtaProjekt.getText().trim();
    
        if (searchInput.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ange ett projekt att söka efter.");
        return;    
    }

    try { 
       String sql = "SELECT projektnamn, startdatum, status" +
                    "FROM projekt " +
                    "WHERE projektnamn LIKE '%" + searchInput + "%' " +
                    "OR startdatum LIKE '%" + searchInput + "%' " +
                    "OR status LIKE '%" + searchInput + "%'";
                   


        ArrayList<HashMap<String, String>> countries = idb.fetchRows(sql);

        DefaultTableModel model = (DefaultTableModel) TableProjekt.getModel();
        model.setRowCount(0);

        if (countries != null && !countries.isEmpty()) {
           for (HashMap<String, String> country : countries) {
             model.addRow(new Object[]{
                  country.get("projektnamn"),
                  country.get("startdatum"),
                  country.get("status"),
                 //country.get(""),
                 
              });
           }
       } else {
             JOptionPane.showMessageDialog(this, "Inga resultat hittades för: " + searchInput);
             
       }

       
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Ett fel inträffade vid sökning: " + ex.getMessage());
        ex.printStackTrace();
      }
                                                
    }//GEN-LAST:event_BtnHamtaProjektActionPerformed

    
    private void loadProjectData() {
    try {
        // SQL-fråga för att hämta projektdata
        String sql = "SELECT projektnamn, startdatum, status, pid FROM projekt";
        ArrayList<HashMap<String, String>> results = idb.fetchRows(sql);

        if (results != null && !results.isEmpty()) {
            // Rensa tabellen innan du fyller den
            DefaultTableModel model = (DefaultTableModel) TableProjekt.getModel();
            model.setRowCount(0);

            // Fyll tabellen med projektdata
            for (HashMap<String, String> row : results) {
                model.addRow(new Object[]{
                    row.get("projektnamn"),
                    row.get("startdatum"),
                    row.get("status"),
                    row.get("pid")
                });
            }
        } else {
            JOptionPane.showMessageDialog(this, "Inga projekt hittades.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Ett fel inträffade vid hämtning av data: " + ex.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HandlaggareProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HandlaggareProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HandlaggareProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HandlaggareProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MinaProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHamtaProjekt;
    private javax.swing.JButton BtnTbxFrånProjekt;
    private javax.swing.JLabel JlrubrikProjekt;
    private javax.swing.JTable TableProjekt;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfHamtaProjekt;
    // End of variables declaration//GEN-END:variables
}