/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel; 
import javax.swing.JOptionPane;
import oru.inf.InfException;
import oru.inf.InfDB;
import java.util.HashMap;

/**
 *
 * @author Tyson
 */
public class HandlaggareSokning extends javax.swing.JFrame {
private InfDB idb;
    /**
     * Creates new form HandlaggareSokning
     */
    public HandlaggareSokning(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    private HandlaggareSokning() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableHandlaggareSok = new javax.swing.JTable();
        tfSokNamn = new javax.swing.JTextField();
        jLAnge = new javax.swing.JLabel();
        BtnTillbaka = new javax.swing.JButton();
        jlSokning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnSok.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnSok.setForeground(new java.awt.Color(0, 0, 102));
        BtnSok.setText("Sök");
        BtnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSokActionPerformed(evt);
            }
        });

        TableHandlaggareSok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aid", "Fornamn", "Efternamn", "Adress", "Epost", "Telefon", "Anstallningsdatum"
            }
        ));
        jScrollPane1.setViewportView(TableHandlaggareSok);

        tfSokNamn.setActionCommand("<Not Set>");
        tfSokNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSokNamnActionPerformed(evt);
            }
        });

        jLAnge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLAnge.setText("Ange Namn eller Epost");

        BtnTillbaka.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BtnTillbaka.setForeground(new java.awt.Color(0, 0, 102));
        BtnTillbaka.setText("Tillbaka");
        BtnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTillbakaActionPerformed(evt);
            }
        });

        jlSokning.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jlSokning.setText("Sökning av handläggare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnTillbaka)
                        .addGap(153, 153, 153)
                        .addComponent(jlSokning))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfSokNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSok, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLAnge, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTillbaka)
                    .addComponent(jlSokning))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLAnge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSokNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnSok)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSokActionPerformed
        String searchInput = tfSokNamn.getText();
          
        if (searchInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ange en ny e-post eller namn att söka med.");
            return;    
        }
        
        if (!searchInput.matches("^[a-zA-ZåäöÅÄÖ ]+$") && !searchInput.contains("@")) {
            JOptionPane.showMessageDialog(this, "Ange ett giltigt namn eller epost.");
            return;
        }
        
        try { 
        String sql = "SELECT anstalld.aid, anstalld.fornamn, anstalld.efternamn, anstalld.adress, anstalld.epost, anstalld.telefon, anstalld.anstallningsdatum, anstalld.avdelning " +
                     "FROM handlaggare " +
                     "JOIN anstalld ON handlaggare.aid = anstalld.aid " +
                     "WHERE CONCAT(anstalld.fornamn, ' ', anstalld.efternamn) LIKE '%" + searchInput + "%' OR anstalld.epost LIKE '%" + searchInput + "%'";
        
        ArrayList<HashMap<String, String>> employees = idb.fetchRows(sql);
        
        
        DefaultTableModel model = (DefaultTableModel) TableHandlaggareSok.getModel();
        model.setRowCount(0);

        if (employees != null && !employees.isEmpty()) {
            for (HashMap<String, String> employee : employees) {
                model.addRow(new Object [] {
                    employee.get("aid"),
                    employee.get("fornamn"),
                    employee.get("efternamn"),
                    employee.get("adress"),
                    employee.get("epost"),
                    employee.get("telefon"),
                    employee.get("anstallningsdatum"),
                    employee.get("avdelning")
                });
            } 
        }else {
            JOptionPane.showMessageDialog(this, "Inga resultat hittades för: " + searchInput);
        }
        
    } catch (InfException ex) {
         JOptionPane.showMessageDialog(this, "Ett fel inträffade vid sökning: " + ex.getMessage());  
        
        }
         
       
    }//GEN-LAST:event_BtnSokActionPerformed

    private void tfSokNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSokNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSokNamnActionPerformed

    private void BtnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTillbakaActionPerformed
        new HandlaggareMeny(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HandlaggareSokning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HandlaggareSokning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HandlaggareSokning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HandlaggareSokning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HandlaggareSokning().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSok;
    private javax.swing.JButton BtnTillbaka;
    private javax.swing.JTable TableHandlaggareSok;
    private javax.swing.JLabel jLAnge;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlSokning;
    private javax.swing.JTextField tfSokNamn;
    // End of variables declaration//GEN-END:variables

    private static class Validator {

        private static boolean isValidName(String searchInput) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public Validator() {
        }
    }

    private static class jTable2 {

        private static void setModel(DefaultTableModel model) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }



        public jTable2() {
        }
    }
}
