/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author seansiik
 */
public class MenyAdmin extends javax.swing.JFrame {

        private InfDB idb;
        private String inloggadAnvandare;
    /**
     * Creates new form Meny
     */
    public MenyAdmin(InfDB idb, String inloggadAnvandare) {
        initComponents();
        this.idb = idb;
        this.inloggadAnvandare = inloggadAnvandare;
        lblInloggadAnvandare.setText(inloggadAnvandare);
    }
              
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggadAnvandare = new javax.swing.JLabel();
        btnMinaUpp = new javax.swing.JButton();
        jLMenyAdmin = new javax.swing.JLabel();
        BtnAvdelning = new javax.swing.JButton();
        BtnProjekt = new javax.swing.JButton();
        BtnAnstallda = new javax.swing.JButton();
        BtnPartners = new javax.swing.JButton();
        BtnTillbakaInloggning = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        btnMinaUpp.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        btnMinaUpp.setText("Mina Uppgifter");
        btnMinaUpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinaUppActionPerformed(evt);
            }
        });

        jLMenyAdmin.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLMenyAdmin.setText("Meny Administratör");

        BtnAvdelning.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        BtnAvdelning.setText("Avdelning");

        BtnProjekt.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        BtnProjekt.setText("Projekt");
        BtnProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProjektActionPerformed(evt);
            }
        });

        BtnAnstallda.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        BtnAnstallda.setText("Anställda");
        BtnAnstallda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnstalldaActionPerformed(evt);
            }
        });

        BtnPartners.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        BtnPartners.setText("Partners");
        BtnPartners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPartnersActionPerformed(evt);
            }
        });

        BtnTillbakaInloggning.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        BtnTillbakaInloggning.setForeground(new java.awt.Color(0, 0, 102));
        BtnTillbakaInloggning.setText("Tillbaka");
        BtnTillbakaInloggning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTillbakaInloggningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(lblInloggadAnvandare))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnAvdelning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAnstallda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnPartners, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMinaUpp, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                        .addGap(127, 127, 127)
                        .addComponent(BtnTillbakaInloggning, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLMenyAdmin)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLMenyAdmin)
                .addGap(81, 81, 81)
                .addComponent(BtnAvdelning)
                .addGap(18, 18, 18)
                .addComponent(BtnAnstallda)
                .addGap(18, 18, 18)
                .addComponent(BtnPartners)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(BtnProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInloggadAnvandare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinaUpp)
                    .addComponent(BtnTillbakaInloggning))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinaUppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaUppActionPerformed
         new MinaUppgifter(idb, inloggadAnvandare).setVisible(true);

    }//GEN-LAST:event_btnMinaUppActionPerformed

    private void BtnPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPartnersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPartnersActionPerformed

    private void BtnProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProjektActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnProjektActionPerformed

    private void BtnAnstalldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnstalldaActionPerformed
        new Mainframe1(idb).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAnstalldaActionPerformed

    private void BtnTillbakaInloggningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTillbakaInloggningActionPerformed
        InloggningAdmin inloggning = new InloggningAdmin(idb);
        inloggning.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTillbakaInloggningActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
   
    InfDB idb = null;
    String inloggadAnvandare = "user@example.com"; 

   
    try {
        idb = new InfDB("databas.db");
        System.out.println("Anslutning till databasen lyckades!");
    } catch (InfException ex) {
        System.out.println("Fel vid anslutning till databasen: " + ex.getMessage());
        return;  
    }
    
   
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            
            //new MenyAdmin(idb, inloggadAnvandare).setVisible(true);
        }
    });
} 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnstallda;
    private javax.swing.JButton BtnAvdelning;
    private javax.swing.JButton BtnPartners;
    private javax.swing.JButton BtnProjekt;
    private javax.swing.JButton BtnTillbakaInloggning;
    private javax.swing.JButton btnMinaUpp;
    private javax.swing.JLabel jLMenyAdmin;
    private javax.swing.JLabel lblInloggadAnvandare;
    // End of variables declaration//GEN-END:variables
}
