/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author seansiik
 */
public class MenyAdmin extends javax.swing.JFrame {

        private InfDB idb;
      
    /**
     * Creates new form Meny
     */
    public MenyAdmin(InfDB idb) {
        initComponents();
        this.idb = idb;
      
    }
              
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggadAnvandare = new javax.swing.JLabel();
        jLMenyAdmin = new javax.swing.JLabel();
        BtnAvdelning = new javax.swing.JButton();
        BtnProjekt = new javax.swing.JButton();
        BtnAnstallda = new javax.swing.JButton();
        BtnPartners = new javax.swing.JButton();
        BtnTillbakaInloggning = new javax.swing.JButton();
        BtnLand = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        jLMenyAdmin.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        jLMenyAdmin.setText("Meny Administratör");

        BtnAvdelning.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        BtnAvdelning.setText("Avdelning");
        BtnAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAvdelningActionPerformed(evt);
            }
        });

        BtnProjekt.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        BtnProjekt.setText("Projekt");
        BtnProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProjektActionPerformed(evt);
            }
        });

        BtnAnstallda.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        BtnAnstallda.setText("Anställda");
        BtnAnstallda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnstalldaActionPerformed(evt);
            }
        });

        BtnPartners.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        BtnPartners.setText("Partners");
        BtnPartners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPartnersActionPerformed(evt);
            }
        });

        BtnTillbakaInloggning.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        BtnTillbakaInloggning.setForeground(new java.awt.Color(0, 0, 102));
        BtnTillbakaInloggning.setText("Tillbaka");
        BtnTillbakaInloggning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTillbakaInloggningActionPerformed(evt);
            }
        });

        BtnLand.setFont(new java.awt.Font("Times New Roman", 1, 50)); // NOI18N
        BtnLand.setText("Land");
        BtnLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLMenyAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnAnstallda, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTillbakaInloggning, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(lblInloggadAnvandare)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnPartners, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(BtnProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(BtnLand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLMenyAdmin)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAvdelning)
                    .addComponent(BtnLand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAnstallda)
                    .addComponent(BtnPartners))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTillbakaInloggning)
                    .addComponent(BtnProjekt))
                .addGap(91, 91, 91)
                .addComponent(lblInloggadAnvandare)
                .addGap(271, 271, 271))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPartnersActionPerformed
                  

    }//GEN-LAST:event_BtnPartnersActionPerformed

    private void BtnProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProjektActionPerformed
                    

    }//GEN-LAST:event_BtnProjektActionPerformed

    private void BtnAnstalldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnstalldaActionPerformed
             new AdminMedarbetare(idb).setVisible(true); 


            
    }//GEN-LAST:event_BtnAnstalldaActionPerformed

    private void BtnTillbakaInloggningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTillbakaInloggningActionPerformed
            InloggningAdmin inloggning = new InloggningAdmin(idb);
            inloggning.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BtnTillbakaInloggningActionPerformed

    private void BtnAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAvdelningActionPerformed
                  
    }//GEN-LAST:event_BtnAvdelningActionPerformed

    private void BtnLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLandActionPerformed
            new AdminLand(idb).setVisible(true); 
    }//GEN-LAST:event_BtnLandActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
   
    InfDB idb = null;
    

   
    try {
        idb = new InfDB("databas.db");
        System.out.println("Anslutning till databasen lyckades!");
    } catch (InfException ex) {
        System.out.println("Fel vid anslutning till databasen: " + ex.getMessage());
        return;  
    }
    
   
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            //new MenyAdmin().setVisible(true);
        }
    });
} 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnstallda;
    private javax.swing.JButton BtnAvdelning;
    private javax.swing.JButton BtnLand;
    private javax.swing.JButton BtnPartners;
    private javax.swing.JButton BtnProjekt;
    private javax.swing.JButton BtnTillbakaInloggning;
    private javax.swing.JLabel jLMenyAdmin;
    private javax.swing.JLabel lblInloggadAnvandare;
    // End of variables declaration//GEN-END:variables
}
