/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;


import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;


public class Startsida extends javax.swing.JFrame {

    private InfDB idb;
    
    public Startsida(InfDB idb) {
        this.idb = idb;
        initComponents();
        
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLValkommen = new javax.swing.JLabel();
        BtnAdmin = new javax.swing.JButton();
        BtnHandlaggare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));

        jLValkommen.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLValkommen.setText("Välkommen");

        BtnAdmin.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BtnAdmin.setText("Administratör");
        BtnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdminActionPerformed(evt);
            }
        });

        BtnHandlaggare.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BtnHandlaggare.setText("Handläggare");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLValkommen, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(BtnAdmin)
                        .addGap(194, 194, 194)
                        .addComponent(BtnHandlaggare)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLValkommen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdmin)
                    .addComponent(BtnHandlaggare))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdminActionPerformed
        new Inloggning(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAdminActionPerformed
    
    private void BtnHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {
        new Inloggning(idb).setVisible(true);
        this.dispose();

    }
    
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            InfDB idb = new InfDB("C:\\path\\to\\database.fdb");
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Startsida(idb).setVisible(true);
                }
            });
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Databasfel: " + e.getMessage());
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdmin;
    private javax.swing.JButton BtnHandlaggare;
    private javax.swing.JLabel jLValkommen;
    // End of variables declaration//GEN-END:variables
}
