/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;


import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;


public class Startsida extends javax.swing.JFrame {

    private InfDB idb;
    
    public Startsida(InfDB idb) {
        this.idb = idb;
        initComponents();
        
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLValkommen = new javax.swing.JLabel();
        BtnAdmin = new javax.swing.JButton();
        BtnHandlaggare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        jLValkommen.setBackground(new java.awt.Color(255, 255, 255));
        jLValkommen.setFont(new java.awt.Font("Xingkai SC", 1, 100)); // NOI18N
        jLValkommen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLValkommen.setText("Välkommen");

        BtnAdmin.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        BtnAdmin.setText("Administratör");
        BtnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdminActionPerformed(evt);
            }
        });

        BtnHandlaggare.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        BtnHandlaggare.setText("Handläggare");
        BtnHandlaggare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHandlaggareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(BtnHandlaggare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(BtnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLValkommen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLValkommen)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnHandlaggare)
                    .addComponent(BtnAdmin))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdminActionPerformed
        new AdminInloggning(idb).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAdminActionPerformed

    private void BtnHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHandlaggareActionPerformed
        new HandlaggareInloggning(idb).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BtnHandlaggareActionPerformed


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            InfDB idb = new InfDB("C:\\path\\to\\database.fdb");
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Startsida(idb).setVisible(true);
                }
            });
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Databasfel: " + e.getMessage());
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdmin;
    private javax.swing.JButton BtnHandlaggare;
    private javax.swing.JLabel jLValkommen;
    // End of variables declaration//GEN-END:variables
}
